name: Core
main: Robster858\Core\main
version: 0.0.1
api: 3.0.0
authors:
  - "Robster858"
  - "ExZeEZ"
commands:
  day:
    description: "Set the time to day"
    permission: "time.cmd"

  night:
    description: "Set the time to night"
    permission: "time.cmd"
